<?php

/**
 * @file
 * Hooks implementation for pantheon_next module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_delete().
 */
function pantheon_next_entity_delete(EntityInterface $entity) {
  $storage = \Drupal::entityTypeManager()->getStorage('pantheon_next');
  if ($entity->getEntityTypeId() == 'next_site') {
    $entities = $storage->loadByProperties(['next_site' => $entity->id()]);
    foreach ($entities as $entity) {
      $entity->delete();
    }
  }
  if ($entity->getEntityTypeId() == 'consumer') {
    $entities = $storage->loadByProperties(['consumer' => $entity->id()]);
    foreach ($entities as $entity) {
      $entity->delete();
    }
  }

  // When a pantheon_next entity is deleted, cascade deletion to the referenced
  // next_site and consumer entity.
  /** @var \Drupal\pantheon_next\Entity\PantheonNextInterface $entity */
  if ($entity->getEntityTypeId() === 'pantheon_next') {
    if ($next_site = $entity->getNextSite()) {
      $next_site->delete();
    }
    if ($consumer = $entity->getConsumer()) {
      $consumer->delete();
    }
  }
}
